config:
  webhook:
    commandWebhookUrl: ""
    playtimeWebhookUrl: ""
    avatarUrl: "https://cdn.discordapp.com/embed/avatars/index.png"
    CommandLoggerUsername: "Command Logger"
    PlaytimeLoggerUsername: "Playtime Logger"
  MessageOfTheDay:
    enabled: true
    defaultMessage: "Welcome to the server! Enjoy your stay!"
    maintenanceMessage: "The server is currently under maintenance. Please check back later."

  joinBuffer:
    buffer: 30
  whitelists:
    Admins:
      - "Sunnit_m"
