config:
  webhook:
    url: ""
    avatarUrl: "https://cdn.discordapp.com/embed/avatars/index.png"
    CommandLoggerUsername: "Command Logger"
    PlaytimeLoggerUsername: "Playtime Logger"
    HandshakeLoggerUsername: "Server Handshake Logger"
    SparkLoggerUsername: "Spark Logger"

  joinBuffer:
    buffer: 30
    message: "You need to wait a little before attempting to join the server again."

whitelists:
  Admins:
    - "Sunnit_m"

  Mods:
    enabled: true
    noHandshakeMessage: "Handshake failed, please update your mods. If the problem persists, contact an admin."
    handshakeTolerance: 5
    whitelistedMods:
      Required:
        - "modid:modname"
      Optional:
        - "modid:modname"